### ISSUE TITLE
Tag Images with version Numbers

### ISSUE THREAD

**Issue by gregkeys** [crossbario/crossbar-docker#11]
When building the docker images can you add tags which correspond to the version release.

**Comment by agronholm** [comment]
Yes, since Crossbar may at any time be updated with a backwards incompatible release (as 0.13 was), I'd like my builds not to break because the "latest" tag now refers to an incompatible version. So crossbario/crossbar:0.13 would work nicely for me.

**Comment by oberstet** [comment]
Agreed. We really should do that

**Comment by oberstet** [comment]
Fixed. All images now have version number tags.
