### ISSUE TITLE
error in docker pull

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar-docker#17]
Following the instructions from ReadMe - but getting the below error:
````
$ sudo docker pull crossbario/autobahn-cpp:clang
Pulling repository docker.io/crossbario/autobahn-cpp
Tag clang not found in repository docker.io/crossbario/autobahn-cpp
````

The `docker pull crossbario/crossbar` succeeded though

**Comment by KrishnaPG** [comment]
Additionally below error is happening with other commands from read me:
````
$ docker run -it crossbario/autobahn-js node /root/client.js ws://192.168.99.100:8080/ws realm1
Unable to find image 'crossbario/autobahn-js:latest' locally
latest: Pulling from crossbario/autobahn-js

4d06f2521e4f: Already exists
9826b741c0da: Pull complete
8509b76ffdf7: Pull complete
af571db96534: Pull complete
4e608817ffca: Pull complete
Digest: sha256:804b5f77048b76cae715cf42597e222bf04c641f5347aa1a264937647a1f1cc5
Status: Downloaded newer image for crossbario/autobahn-js:latest
module.js:328
    throw err;
    ^

Error: Cannot find module '/root/client.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
````

**Comment by goeddea** [comment]
Thanks for the catches!

- autobahn-cpp:clang does not exist, so removed the reference in the README
- `/root/client.js` is now just `client.js` (and works)

**Comment by KrishnaPG** [comment]
Thank you. The `client.js` worked.

About the `autobahn-cpp`, the command `docker pull crossbario/autobahn-cpp:gcc` worked.

But, the ReadMe does not contain much info on how to use this `autobahn-cpp` docker once it is downloaded. For example, what is the run command for this `autobahn-cpp` docker (similar to the js one) ? Say, I want to play with the `callee` and `caller` examples of the cpp
