### ISSUE TITLE
Feature Request: Add support for Kitematic Volume Mapping

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar-docker#19]
Kitematic volume mapping allows easy access to files from host directly, and it would be great if the web files are mapped this way inside the crossbar images. (One can see some background on this [here](https://docs.docker.com/v1.8/kitematic/userguide/#managing-volumes))

Looks like one need to specify `VOLUME ["/node/web"]` command in the docker to take advantage of this feature (based on the reference example here: https://github.com/kitematic/html/blob/master/Dockerfile)

**Comment by oberstet** [comment]
you don't need this to map volumes
