### ISSUE TITLE
Custom config.json in volume throw "oci runtime error"

### ISSUE THREAD

**Issue by Trouffman** [crossbario/crossbar-docker#32]
When mounting the config.json file into a volume to allow scaling and access to the config file, it will per default create a directory then fail,

`docker run -it --name crossbario -p 8080:8080  -v /somewhere/web/:/node/web/ /somewhere/config/config.json:/node/.crossbar/config.json  crossbario/crossbar`

`Volume : /somewhere/web/:/node/web/`
For static WEB (no problem here IIRC)

`Volume : /somewhere/config/config.json:/node/.crossbar/config.json`
For editing /backing up /deploying the config file.

**To reproduce**
Run the command with NO config.json  :

> docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/somewhere/config/config.json\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/d8313f3f154155a38ecba75c645505c4d6b847fd994b37b5386c80d338183d9e/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/d8313f3f154155a38ecba75c645505c4d6b847fd994b37b5386c80d338183d9e/rootfs/node/.crossbar/config.json\\\" caused \\\"not a directory\\\"\""
> : Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

Indeed it tried to create a directory called config.json/ 

Now try with a default config.json in /somewhere/config/config.json and it will work / take it as the config file.

Example : 
`            "realms": [
                {
                    "name": "hakunamatatah",
`

> [Router         13] Realm 'hakunamatatah' started

** Suggestion **
A. At creation pull a defaul config.json file and create it as a file (But I would rather use Solution B.)
B. Implement a directory for config files (see : https://github.com/crossbario/crossbar/issues/973 )

** EDIT **
This is mostly and error with access right, (that was in root on the test instance), change to the local user and my docker group for the directories and the start the crossbar server.

BUT, it does not get/generate a default config.json which it should.

**Comment by oberstet** [comment]
> When mounting the config.json file into a volume ..

This isn't supported. You have to mount a complete node directory (which is writable)

**Comment by Trouffman** [comment]
Managed to do so with the proper access right i will update / pull request
the details later on.
