### ISSUE TITLE
Crossbar.io and Autobahn ARM images

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-docker#4]
To support Docker on the Pi 2, we would need images for the `armhf` Linux architecture. See [here](https://github.com/docker-library/official-images#architectures-other-than-amd64) and [here](https://hub.docker.com/u/armhf/).

> Note: The Pi 3, being 64-bit, likely will require yet another Linux architecture: `arm64`

**Comment by Hades32** [comment]
Pi3 is 32bit userland. No need for separate builds / images.
FROM resin/rpi-raspbian:jessie
Is a good start.

**Comment by Hades32** [comment]
Scaleway has cheap ARM servers and docker images

**Comment by joernroeder** [comment]
+1 for rPi compatible dockerfiles/packages

**Comment by oberstet** [comment]
@Hades32 32 bit userland .. interesting. wasn't aware. will they change that upcoming?

I didn't have time yet to look more closely into "Docker + Pi" .. what about
* http://blog.hypriot.com/
* https://hub.docker.com/r/hypriot/
* https://github.com/hypriot

Rgd Scaleway .. ideally we'd have something to build images that integrates into our CI .. Travis. Or at least can be started from command line (`make image`) ..

**Comment by joernroeder** [comment]
@oberstet i'm running docker with hypriot on my rPi 2 and rPi 3 and combined with https://github.com/hypriot/docker-machine-hypriot it's dead simple.
Have a look at https://hub.docker.com/r/hypriot/rpi-python/ and https://github.com/hypriot/rpi-alpine-scratch, they should be good starting points.

**Comment by oberstet** [comment]
@joernroeder I'll check that out! Funny: the Hypriot guys have been doing a presentation recently at IoT Meetup Franke (which we co-initiated): http://www.meetup.com/de-DE/IoT-Meetup-Franken/events/229158470/

Sadly, I was unable to attend=( But as the Hypriot guys are from Bamberg, we're gonna see each other anyway;) Bamberg is like 30km from Erlangen (our homebase).

**Comment by oberstet** [comment]
related: https://github.com/docker-library/pypy/issues

**Comment by oberstet** [comment]
Here: https://github.com/crossbario/crossbar-docker/tree/master/crossbar/armhf
