### ISSUE TITLE
Don't run Crossbar as root

### ISSUE THREAD

**Issue by agronholm** [crossbario/crossbar-docker#6]
Running something as root is not considered good practice if the process does not need root privileges.

I've seen varying practices regarding this by established vendors: run as UID 1, 999 or 1000. I would probably opt for 1 (`USER daemon:daemon`).

**Comment by oberstet** [comment]
As long as we make the node directory is owned by `daemon:daemon`, that sounds good and easy!

**Comment by agronholm** [comment]
That's the reason I made /tmp the crossbar home directory -- because the pid file is useless in a Docker container and no logs are written anyway.

**Comment by oberstet** [comment]
I am thinking about making .. what's that thing where you mount a directory from the host inside the container? Anyway, we need to persist things .. eg the node key.

**Comment by agronholm** [comment]
That's a volume. If those node key needs to be persisted, this is something that should be documented on the Docker hub page.

**Comment by oberstet** [comment]
fixed in https://github.com/crossbario/crossbar-docker/commit/914a8114f3baeb5dfe0f1fb80c08ef4bf6ddf74a
